CRITICAL - 2024-06-14 00:02:27 --> ErrorException: Undefined variable $userModel
[Method: POST, Route: api/v1/auth]
in APPPATH\Controllers\Api\V1\Auth.php on line 34.
 1 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $userModel', 'C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\app\\Controllers\\Api\\V1\\Auth.php', 34)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 00:02:35 --> ErrorException: Undefined variable $userModel
[Method: POST, Route: api/v1/auth]
in APPPATH\Controllers\Api\V1\Auth.php on line 34.
 1 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $userModel', 'C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\app\\Controllers\\Api\\V1\\Auth.php', 34)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 00:03:49 --> ErrorException: Undefined variable $userModel
[Method: POST, Route: api/v1/auth]
in APPPATH\Controllers\Api\V1\Auth.php on line 34.
 1 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $userModel', 'C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\app\\Controllers\\Api\\V1\\Auth.php', 34)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
ERROR - 2024-06-14 00:04:20 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^ in C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\Postgre\Connection.php:193
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\Users\\Indate...', 193)
#1 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\Postgre\Connection.php(193): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseConnection.php(722): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\BaseModel.php(610): CodeIgniter\Model->doFind(false, NULL)
#7 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\app\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->find()
#8 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
#9 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
#10 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indate...')
#15 {main}
CRITICAL - 2024-06-14 00:04:20 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^
[Method: POST, Route: api/v1/auth]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
WHERE "username" = :username:
AND "password" = :password:', [...], false)
 2 SYSTEMPATH\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(610): CodeIgniter\Model->doFind(false, null)
 4 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->find()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 00:04:20 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 198.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "user"
WHERE "username" = \'26192023\'
AND "password" = \'gdfgdfgdf\'')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "user"
WHERE "username" = \'26192023\'
AND "password" = \'gdfgdfgdf\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
WHERE "username" = :username:
AND "password" = :password:', [...], false)
 4 SYSTEMPATH\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(610): CodeIgniter\Model->doFind(false, null)
 6 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->find()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 00:04:20 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 193.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^', 'C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\system\\Database\\Postgre\\Connection.php', 193)
 2 SYSTEMPATH\Database\Postgre\Connection.php(193): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "user"
WHERE "username" = \'26192023\'
AND "password" = \'gdfgdfgdf\'')
 3 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "user"
WHERE "username" = \'26192023\'
AND "password" = \'gdfgdfgdf\'')
 4 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "user"
WHERE "username" = \'26192023\'
AND "password" = \'gdfgdfgdf\'')
 5 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
WHERE "username" = :username:
AND "password" = :password:', [...], false)
 6 SYSTEMPATH\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(610): CodeIgniter\Model->doFind(false, null)
 8 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->find()
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
ERROR - 2024-06-14 00:04:44 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^ in C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\Postgre\Connection.php:193
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\Users\\Indate...', 193)
#1 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\Postgre\Connection.php(193): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseConnection.php(722): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Model.php(919): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\app\Controllers\Api\V1\Auth.php(34): CodeIgniter\Model->__call('get', Array)
#7 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
#8 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
#9 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indate...')
#14 {main}
CRITICAL - 2024-06-14 00:04:44 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^
[Method: POST, Route: api/v1/auth]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
WHERE "username" = :username:
AND "password" = :password:', [...], false)
 2 SYSTEMPATH\Model.php(919): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 00:04:44 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 198.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "user"
WHERE "username" = \'26192023\'
AND "password" = \'gdfgdfgdf\'')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "user"
WHERE "username" = \'26192023\'
AND "password" = \'gdfgdfgdf\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
WHERE "username" = :username:
AND "password" = :password:', [...], false)
 4 SYSTEMPATH\Model.php(919): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 00:04:44 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 193.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^', 'C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\system\\Database\\Postgre\\Connection.php', 193)
 2 SYSTEMPATH\Database\Postgre\Connection.php(193): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "user"
WHERE "username" = \'26192023\'
AND "password" = \'gdfgdfgdf\'')
 3 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "user"
WHERE "username" = \'26192023\'
AND "password" = \'gdfgdfgdf\'')
 4 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "user"
WHERE "username" = \'26192023\'
AND "password" = \'gdfgdfgdf\'')
 5 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
WHERE "username" = :username:
AND "password" = :password:', [...], false)
 6 SYSTEMPATH\Model.php(919): CodeIgniter\Database\BaseBuilder->get()
 7 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\Model->__call('get', [])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
ERROR - 2024-06-14 00:05:01 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^ in C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\Postgre\Connection.php:193
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\Users\\Indate...', 193)
#1 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\Postgre\Connection.php(193): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseConnection.php(722): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\app\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->findAll()
#8 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
#9 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
#10 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indate...')
#15 {main}
CRITICAL - 2024-06-14 00:05:01 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^
[Method: POST, Route: api/v1/auth]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
WHERE "username" = :username:
AND "password" = :password:', [...], false)
 2 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 00:05:01 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 198.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "user"
WHERE "username" = \'26192023\'
AND "password" = \'gdfgdfgdf\'')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "user"
WHERE "username" = \'26192023\'
AND "password" = \'gdfgdfgdf\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
WHERE "username" = :username:
AND "password" = :password:', [...], false)
 4 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->findAll()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 00:05:01 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 193.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^', 'C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\system\\Database\\Postgre\\Connection.php', 193)
 2 SYSTEMPATH\Database\Postgre\Connection.php(193): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "user"
WHERE "username" = \'26192023\'
AND "password" = \'gdfgdfgdf\'')
 3 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "user"
WHERE "username" = \'26192023\'
AND "password" = \'gdfgdfgdf\'')
 4 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "user"
WHERE "username" = \'26192023\'
AND "password" = \'gdfgdfgdf\'')
 5 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
WHERE "username" = :username:
AND "password" = :password:', [...], false)
 6 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 8 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->findAll()
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
ERROR - 2024-06-14 00:05:11 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^ in C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\Postgre\Connection.php:193
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\Users\\Indate...', 193)
#1 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\Postgre\Connection.php(193): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseConnection.php(722): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\app\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->findAll()
#8 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
#9 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
#10 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indate...')
#15 {main}
CRITICAL - 2024-06-14 00:05:11 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^
[Method: POST, Route: api/v1/auth]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
WHERE "username" = :username:', [...], false)
 2 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 00:05:11 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 198.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "user"
WHERE "username" = \'26192023\'')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "user"
WHERE "username" = \'26192023\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
WHERE "username" = :username:', [...], false)
 4 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->findAll()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 00:05:11 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 193.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^', 'C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\system\\Database\\Postgre\\Connection.php', 193)
 2 SYSTEMPATH\Database\Postgre\Connection.php(193): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "user"
WHERE "username" = \'26192023\'')
 3 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "user"
WHERE "username" = \'26192023\'')
 4 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "user"
WHERE "username" = \'26192023\'')
 5 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
WHERE "username" = :username:', [...], false)
 6 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 8 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->findAll()
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
ERROR - 2024-06-14 00:05:12 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^ in C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\Postgre\Connection.php:193
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\Users\\Indate...', 193)
#1 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\Postgre\Connection.php(193): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseConnection.php(722): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\app\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->findAll()
#8 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
#9 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
#10 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indate...')
#15 {main}
CRITICAL - 2024-06-14 00:05:12 --> CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^
[Method: POST, Route: api/v1/auth]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
WHERE "username" = :username:', [...], false)
 2 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 00:05:12 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 198.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "user"
WHERE "username" = \'26192023\'')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "user"
WHERE "username" = \'26192023\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
WHERE "username" = :username:', [...], false)
 4 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->findAll()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 00:05:12 --> [Caused by] ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 193.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la relación «user»
LINE 2: FROM &quot;user&quot;
             ^', 'C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\system\\Database\\Postgre\\Connection.php', 193)
 2 SYSTEMPATH\Database\Postgre\Connection.php(193): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "user"
WHERE "username" = \'26192023\'')
 3 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "user"
WHERE "username" = \'26192023\'')
 4 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "user"
WHERE "username" = \'26192023\'')
 5 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "user"
WHERE "username" = :username:', [...], false)
 6 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 8 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\BaseModel->findAll()
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:02:56 --> ErrorException: Undefined variable $users
[Method: POST, Route: api/v1/auth]
in APPPATH\Controllers\Api\V1\Auth.php on line 36.
 1 APPPATH\Controllers\Api\V1\Auth.php(36): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $users', 'C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\app\\Controllers\\Api\\V1\\Auth.php', 36)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:03:18 --> ErrorException: Undefined variable $users
[Method: POST, Route: api/v1/auth]
in APPPATH\Controllers\Api\V1\Auth.php on line 36.
 1 APPPATH\Controllers\Api\V1\Auth.php(36): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $users', 'C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\app\\Controllers\\Api\\V1\\Auth.php', 36)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:03:53 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseBuilder.php on line 760
[Method: POST, Route: api/v1/auth]
in SYSTEMPATH\Database\BaseBuilder.php on line 3453.
 1 SYSTEMPATH\Database\BaseBuilder.php(760): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(701): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], [...], 'AND ', true)
 3 SYSTEMPATH\Model.php(919): CodeIgniter\Database\BaseBuilder->where([...], [...])
 4 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:12:14 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseBuilder.php on line 760
[Method: POST, Route: api/v1/auth]
in SYSTEMPATH\Database\BaseBuilder.php on line 3453.
 1 SYSTEMPATH\Database\BaseBuilder.php(760): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(701): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(919): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:12:26 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseBuilder.php on line 760
[Method: POST, Route: api/v1/auth]
in SYSTEMPATH\Database\BaseBuilder.php on line 3453.
 1 SYSTEMPATH\Database\BaseBuilder.php(760): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(701): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(919): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:12:40 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseBuilder.php on line 760
[Method: POST, Route: api/v1/auth]
in SYSTEMPATH\Database\BaseBuilder.php on line 3453.
 1 SYSTEMPATH\Database\BaseBuilder.php(760): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(701): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(919): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:12:41 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseBuilder.php on line 760
[Method: POST, Route: api/v1/auth]
in SYSTEMPATH\Database\BaseBuilder.php on line 3453.
 1 SYSTEMPATH\Database\BaseBuilder.php(760): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(701): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(919): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:12:42 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseBuilder.php on line 760
[Method: POST, Route: api/v1/auth]
in SYSTEMPATH\Database\BaseBuilder.php on line 3453.
 1 SYSTEMPATH\Database\BaseBuilder.php(760): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(701): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(919): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:12:42 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseBuilder.php on line 760
[Method: POST, Route: api/v1/auth]
in SYSTEMPATH\Database\BaseBuilder.php on line 3453.
 1 SYSTEMPATH\Database\BaseBuilder.php(760): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(701): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(919): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:12:48 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\Users\Indatech\Desktop\Alex\diplomado\proyecto\backend-proyecto\system\Database\BaseBuilder.php on line 760
[Method: POST, Route: api/v1/auth]
in SYSTEMPATH\Database\BaseBuilder.php on line 3453.
 1 SYSTEMPATH\Database\BaseBuilder.php(760): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(701): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(919): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\Api\V1\Auth.php(34): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:13:02 --> ErrorException: Attempt to read property "password" on array
[Method: POST, Route: api/v1/auth]
in APPPATH\Controllers\Api\V1\Auth.php on line 40.
 1 APPPATH\Controllers\Api\V1\Auth.php(40): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "password" on array', 'C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\app\\Controllers\\Api\\V1\\Auth.php', 40)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:13:05 --> ErrorException: Attempt to read property "password" on array
[Method: POST, Route: api/v1/auth]
in APPPATH\Controllers\Api\V1\Auth.php on line 40.
 1 APPPATH\Controllers\Api\V1\Auth.php(40): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "password" on array', 'C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\app\\Controllers\\Api\\V1\\Auth.php', 40)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:13:06 --> ErrorException: Attempt to read property "password" on array
[Method: POST, Route: api/v1/auth]
in APPPATH\Controllers\Api\V1\Auth.php on line 40.
 1 APPPATH\Controllers\Api\V1\Auth.php(40): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "password" on array', 'C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\app\\Controllers\\Api\\V1\\Auth.php', 40)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:13:23 --> ErrorException: Attempt to read property "password" on array
[Method: POST, Route: api/v1/auth]
in APPPATH\Controllers\Api\V1\Auth.php on line 40.
 1 APPPATH\Controllers\Api\V1\Auth.php(40): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "password" on array', 'C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\app\\Controllers\\Api\\V1\\Auth.php', 40)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:13:26 --> ErrorException: Attempt to read property "password" on array
[Method: POST, Route: api/v1/auth]
in APPPATH\Controllers\Api\V1\Auth.php on line 40.
 1 APPPATH\Controllers\Api\V1\Auth.php(40): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "password" on array', 'C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\app\\Controllers\\Api\\V1\\Auth.php', 40)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\V1\Auth->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:16:24 --> ParseError: syntax error, unexpected token "*"
[Method: POST, Route: api/v1/auth]
in APPPATH\Controllers\Api\V1\Auth.php on line 43.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\app\\Controllers\\Api\\V1\\Auth.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Api\\V1\\Auth')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Api\\V1\\Auth')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\Api\\V1\\Auth', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:16:29 --> ParseError: syntax error, unexpected token "*"
[Method: POST, Route: api/v1/auth]
in APPPATH\Controllers\Api\V1\Auth.php on line 43.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\app\\Controllers\\Api\\V1\\Auth.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Api\\V1\\Auth')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Api\\V1\\Auth')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\Api\\V1\\Auth', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
CRITICAL - 2024-06-14 01:16:32 --> ParseError: syntax error, unexpected token "*"
[Method: POST, Route: api/v1/auth]
in APPPATH\Controllers\Api\V1\Auth.php on line 43.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\app\\Controllers\\Api\\V1\\Auth.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Api\\V1\\Auth')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Api\\V1\\Auth')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\Api\\V1\\Auth', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\Indatech\\Desktop\\Alex\\diplomado\\proyecto\\backend-proyecto\\public\\index.php')
